runtime: python310

entrypoint: gunicorn -b :$PORT main:app
instance_class: F4_1G 
env_variables:
  MONGO_URI: ${MONGO_URL}

handlers:
- url: /static
  static_dir: app/static

- url: /.*
  script: auto
